version: '3'
services:
  planner:
    build:
      context : .
      dockerfile : ./dockerfiles/planner.dockerfile
    ports: 
      - "3000:3000"
    environment:
      PORT: 3000
      TASKS: 4

  worker:
    build: 
      context : .
      dockerfile : ./dockerfiles/worker.dockerfile
    container_name: worker
    ports : 
      - "8080:8080"
    environment:
      # PORT: 8080
      MULT: true
      ADD: true
      PLANNER: 'http://planner:3000'

  worker1:
    build: 
      context : .
      dockerfile : ./dockerfiles/worker.dockerfile
    container_name: worker1
    ports : 
      - "8070:8080"
    environment:
      PORT: 8070
      MULT: true
      ADD: true
      PLANNER: 'http://planner:3000'
